### ISSUE TITLE
Is there a documented standard for figlet fonts and the rendering?

### ISSUE THREAD

**Issue by ModProg** [cmatsuoka/figlet#21]
I'm currently working on a rust implementation as a library https://github.com/togglebyte/figglebit, and did not find a whole lot of documentation on the actual standard, if you can call it that.

**Comment by ModProg** [comment]
Oh well right after writing this I found: https://patorjk.com/software/taag/docs/figfont.txt

**Comment by Potherca** [comment]
@ModProg So this issue can now be closed, correct?
